### PR TITLE
Add configuration file selector

### PR DESCRIPTION
**Pull request by geronimo-iia**
- add '--configurations' options to select a configuration file other than brume.yml
- 'brume.yml' is the default one
- all local path specified in yaml file will be resolved from location of this file
- refactorization of stack and sub stack extraction 
- bug fix: error management on update stack method

### CODE REVIEW

**Comment by flou** [comment]
I am not really a huge fan of using `global` statements for the configuration. I'll take a look at how this could be implemented without globals.

**Comment by flou** [comment]
@geronimo-iia I believe all issues should be resolved in the latest version of brume, especially the configuration switch `-c/--config` with `brume.yml` as the default.

If not feel free to reply on this PR.

**Comment by geronimo-iia** [comment]
Hi @flou 
I will do some test/merge from last version, see you soon

**Comment by geronimo-iia** [comment]
@flou hi, for swicth config and default brume.yml it's ok

It missing some cfn function as basic service, and i have to check other refacto

**Comment by geronimo-iia** [comment]
It missing cfn function, stack walker, etc... 
I'm closing this issue, your last change conflict with my pull request

**Pull request closed without merging**
